### ISSUE TITLE
question ... Python 3 support ?

### ISSUE THREAD

**Issue by fenix011** [fredrikloch/JekyllToHugo#9]
Hi Frederik, 

 You say it's tested on v2.7
 By chance, does this useful tool have Python 3 support ?

thanks, thanks, thanks

F

**Comment by fredrikloch** [comment]
I've not done any further development on this script apart from merging some PR's since 2016, but from a quick glance I don't think there is anything that should cause issues. I would suggest testing on a copy of your data to be sure though.
